trigger:
  branches:
    include:
      - main
  paths:
    include:
      - main/main.py
      - visa/visa.py
pool:
  name: my-ubuntu-pool  # Specify the name of your custom agent pool here

steps:
  - script: |
      git clone https://github.com/Guyashkenazi6/cardealership.git
      cd cardealership/main  # Change to the directory containing the Dockerfile
      docker build -t $(DOCKERHUB_USERNAME)/vehicle_management_server-main .
      echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
      docker push $(DOCKERHUB_USERNAME)/vehicle_management_server-main
    displayName: 'Build and Push Docker Image'

  - script: |
      git clone https://github.com/Guyashkenazi6/cardealership.git
      cd cardealership/visa  # Change to the directory containing the Dockerfile
      docker build -t $(DOCKERHUB_USERNAME)/vehicle_management_server-visa .
      echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
      docker push $(DOCKERHUB_USERNAME)/vehicle_management_server-visa
    displayName: 'Build and Push Docker Image'

