version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  visa:
    build:
      context: Vehicle_management_server\visa
    ports:
      - "9010:9010"
    networks:
      - mynetwork
    depends_on:
      - mongodb

  main:
    build:
      context: Vehicle_management_server\main
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    depends_on:
      - mongodb
      - visa

networks:
  mynetwork:
    driver: bridge
